parameters:
    json_api.metadata.annotation_driver.class: Mango\Bundle\JsonApiBundle\Configuration\Metadata\Driver\AnnotationDriver
    json_api.metadata.yaml_driver.class: Mango\Bundle\JsonApiBundle\Configuration\Metadata\Driver\YamlDriver

services:

    json_api.metadata.annotation_driver:
        class: '%json_api.metadata.annotation_driver.class%'
        public: false
        arguments:
            - '@annotations.reader'
            - '@jms_serializer.naming_strategy'
            - '@jms_serializer.type_parser'

    json_api.metadata.yaml_driver:
        class: '%json_api.metadata.yaml_driver.class%'
        arguments:
            - '@jms_serializer.metadata.file_locator'

    json_api.metadata.chain_driver:
        class: Metadata\Driver\DriverChain
        public: false
        arguments:
            - ['@json_api.metadata.yaml_driver', '@json_api.metadata.annotation_driver']

    jms_serializer.metadata_driver:
        alias: json_api.metadata.chain_driver
        public: true

    json_api.serializer.relationship_exclusion_strategy:
        class: 'Mango\Bundle\JsonApiBundle\Serializer\Exclusion\RelationshipExclusionStrategy'
        arguments:
            - '@jms_serializer.metadata_factory'

    json_api.accessor_strategy.default:
        class: 'Mango\Bundle\JsonApiBundle\Serializer\Accessor\DefaultAccessorStrategy'
        decorates: 'jms_serializer.accessor_strategy.default'
        arguments:
            - '@json_api.accessor_strategy.default.inner'

    jms_serializer.accessor_strategy:
        alias: json_api.accessor_strategy.default
        public: false
