parameters:
    json_api.listener.json_event_subscriber.class: Mango\Bundle\JsonApiBundle\EventListener\Serializer\JsonEventSubscriber
    jms_serializer.doctrine_object_constructor.class: Mango\Bundle\JsonApiBundle\Serializer\Construction\DoctrineObjectConstructor
    jms_serializer.array_collection_handler.class: Mango\Bundle\JsonApiBundle\Serializer\Handler\ArrayCollectionHandler
    jms_serializer.accessor_strategy.default.class: Mango\Bundle\JsonApiBundle\Serializer\Accessor\DefaultAccessorStrategy

services:

    json_api.listener.json_event_subscriber:
        class: '%json_api.listener.json_event_subscriber.class%'
        arguments:
            - '@jms_serializer.metadata_factory'
            - '@jms_serializer.metadata_factory'
            - '@jms_serializer.naming_strategy'
            - '@request_stack'
            - '@json_api.resolver.base_uri'
        tags:
            - { name: 'jms_serializer.event_subscriber' }

    json_api.serializer.handler.pagerfanta:
        class: 'Mango\Bundle\JsonApiBundle\Serializer\Handler\PagerfantaHandler'
        arguments:
            - '@request_stack'
        tags:
            - { name: 'jms_serializer.subscribing_handler' }

    json_api.resolver.base_uri:
        alias: 'json_api.resolver.base_uri.default'

    json_api.resolver.base_uri.default:
        class: 'Mango\Bundle\JsonApiBundle\Resolver\BaseUri\BaseUriResolver'
        arguments:
            - '@request_stack'
            - '%json_api.base_uri%'

    jms_serializer.json_api_serialization_visitor:
        class: 'Mango\Bundle\JsonApiBundle\Serializer\Visitor\Factory\JsonApiSerializationVisitorFactory'
        arguments:
            - '@jms_serializer.metadata_factory'
            - '%json_api.show_version_info%'
        tags:
            - { name: 'jms_serializer.serialization_visitor', format: 'json:api' }

    jms_serializer.json_api_deserialization_visitor:
        class: 'Mango\Bundle\JsonApiBundle\Serializer\Visitor\Factory\JsonApiDeserializationVisitorFactory'
        tags:
            - { name: 'jms_serializer.deserialization_visitor', format: 'json:api' }

    jms_serializer.json_api_constraint_violation_handler:
        class: 'Mango\Bundle\JsonApiBundle\Serializer\Handler\ConstraintViolationHandler'
        public: true
        tags:
            - { name: 'jms_serializer.subscribing_handler' }

    jms_serializer.json_api_exception_handler:
        class: 'Mango\Bundle\JsonApiBundle\Serializer\Handler\ExceptionHandler'
        public: true
        tags:
            - { name: 'jms_serializer.subscribing_handler' }

    json_api.exception.subscriber:
        class: 'Mango\Bundle\JsonApiBundle\EventListener\ExceptionSubscriber'
        public: true
        arguments:
            - '@jms_serializer'
            - '%json_api.catch_exceptions%'
        calls:
            - [ setLogger, ['@?logger'] ]
        tags:
            - { name: 'kernel.event_subscriber' }

    jms_serializer.handler_registry:
        class: 'Mango\Bundle\JsonApiBundle\Serializer\Handler\LazyRegexHandlerRegistry'
        arguments:
            - '@service_container'

    json_api.request_params.parser.filter_param:
        class: 'Mango\Bundle\JsonApiBundle\RequestParameters\Parser\FilterParamParser'

    json_api.request_params.parser.sort_param:
        class: 'Mango\Bundle\JsonApiBundle\RequestParameters\Parser\SortParamParser'

    json_api.request_params.parser.page_param:
        class: 'Mango\Bundle\JsonApiBundle\RequestParameters\Parser\PageParamParser'

    json_api.request_params.converter.http_request_converter:
        class: 'Mango\Bundle\JsonApiBundle\RequestParameters\Converter\HttpRequestToParametersConverter'
        arguments:
            - '@jms_serializer'
            - '@validator'
            - filter: '@json_api.request_params.parser.filter_param'
              sort: '@json_api.request_params.parser.sort_param'
              page: '@json_api.request_params.parser.page_param'

        tags:
            - {name: 'request.param_converter', converter: 'json_api.request_params.converter.http_request_converter'}

    json_api.datetime_handler:
        class: Mango\Bundle\JsonApiBundle\Serializer\Handler\DateHandler
        arguments:
            - '@jms_serializer.datetime_handler'
        tags:
            - { name: jms_serializer.subscribing_handler }

    json_api.array_collection_handler:
        class: Mango\Bundle\JsonApiBundle\Serializer\Handler\ArrayCollectionHandler
        arguments:
            - '@jms_serializer.array_collection_handler'
        tags:
            - { name: jms_serializer.subscribing_handler }

