language: php

php:
  - 7.2
  - 7.3

env:
  global:
    - PHPUNIT_FLAGS="-v"
    - TARGET=test

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: SYMFONY_REQUIRE='~3.4'
    - php: 7.2
      env: SYMFONY_REQUIRE='~4.0'

    - php: 7.3
      env: SYMFONY_REQUIRE='~3.4'
    - php: 7.3
      env: SYMFONY_REQUIRE='~4.0'

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
  - if ! [ -z "$SYMFONY_REQUIRE" ]; then composer global require symfony/flex dev-master; fi;

install:
  - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction

script:
  - vendor/bin/phpunit ${PHPUNIT_FLAGS}
  - vendor/bin/phpstan analyse || true
